#!/usr/bin/env python3
"""Emit the versioned canonical entry projection export (P2' promotion).

Background: P1 (commit a05bda6, wired into advisory CI as P1-CI at commit
3041178) proved that all 15 governed tables can be projected losslessly into
a three-column canonical view (entry_id / claim_level / source_ref) without
modifying any of the original tables. The 2026-07-31 P2 decision ("P2:
canonical projection promotion, not schema migration" — see PLAN.md) found
that a real schema migration would buy nothing the projection doesn't
already deliver, at a much higher and asymmetric cost, so P2 promotes the
projection itself from an advisory report to a governed, versioned export
instead of rewriting any governed table.

This script reuses scripts/probe_canonical_entry_projection.py's projection
logic (same adapters, same manifest, same gap detection) and writes the
result to exports/canonical_entry_index.yaml as a reviewable, versioned
artifact — analogous to exports/hub_governed_surface_manifest.yaml.

DERIVATIVE ARTIFACT ONLY. This export establishes no claim beyond what
already exists on the governed table entries and their evidence packets
(see the ``claim_ceiling`` block written into the export itself). It never
modifies any of the 15 governed tables or contract/projection_adapters.yaml.

Freshness/drift between this export and the governed tables it is derived
from is enforced by
scripts/validate_canonical_entry_projection_invariants.py, not by this
script.

Usage:
    python scripts/export_canonical_entry_index.py
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

from probe_canonical_entry_projection import (
    MANIFEST_PATH,
    load_adapters,
    load_registered_source_ids,
    project_table,
    validate_adapters,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
EXPORT_PATH = REPO_ROOT / "exports" / "canonical_entry_index.yaml"

EXPORT_HEADER_COMMENT = (
    "# Generated by scripts/export_canonical_entry_index.py — do not hand-edit\n"
    "# the `entries` or `invariants` blocks; regenerate instead.\n"
)


def build_export() -> dict[str, Any]:
    """Regenerate the full canonical entry export from the governed tables.

    Returns the same semantic content every time the 15 governed tables and
    contract/projection_adapters.yaml are unchanged (no timestamp field), so
    callers can compare two builds for equality to detect drift.
    """
    manifest = yaml.safe_load(MANIFEST_PATH.read_text(encoding="utf-8"))
    tables = manifest.get("governed_tables", [])
    adapters = load_adapters()
    registered_source_ids = load_registered_source_ids()

    projected_tables = [project_table(table, adapters) for table in tables]
    projected_by_table_id = {t["table_id"]: t for t in projected_tables}
    adapter_validation = validate_adapters(adapters, projected_by_table_id, registered_source_ids)
    adapter_validation_passed = all(r["passed"] for r in adapter_validation)

    total_entries = sum(t["entry_count"] for t in projected_tables)
    total_ungoverned_id = sum(t["identity_key_ungoverned_count"] for t in projected_tables)
    total_default_claim = sum(t["claim_level_defaulted_count"] for t in projected_tables)
    total_source_gap = sum(t["source_ref_gap_count"] for t in projected_tables)
    lossless = (
        total_ungoverned_id == 0
        and total_default_claim == 0
        and total_source_gap == 0
        and adapter_validation_passed
    )

    entries: list[dict[str, Any]] = []
    for table in projected_tables:
        for row in table["rows"]:
            entry: dict[str, Any] = {
                "entry_id": row["entry_id"],
                "table_id": table["table_id"],
                "claim_level": row["claim_level"],
                "source_ref": row["source_ref"],
            }
            if row.get("evidence_ref"):
                entry["evidence_ref"] = row["evidence_ref"]
            entries.append(entry)

    return {
        "export_id": "canonical_entry_index",
        "export_version": "1.0",
        "export_type": "canonical_entry_projection",
        "generated_from": "scripts/export_canonical_entry_index.py",
        "derived_from": {
            "manifest": "exports/hub_governed_surface_manifest.yaml",
            "adapters": "contract/projection_adapters.yaml",
        },
        "description": (
            "Governed, versioned three-column canonical projection "
            "(entry_id, claim_level, source_ref) across all USB hub governed "
            "tables. DERIVATIVE export only: it establishes no claim beyond "
            "what already exists on the source governed table entry and its "
            "evidence packet. If this export and a governed table entry "
            "ever disagree, the governed table is authoritative and this "
            "export is stale — see "
            "scripts/validate_canonical_entry_projection_invariants.py."
        ),
        "claim_ceiling": {
            "inherits": "spec_reference_only",
            "establishes_no_new_claims": True,
            "cannot_establish": [
                "firmware_behavior",
                "project_specific_truth",
                "observed_device_behavior",
                "vendor_specific_behavior",
                "any_claim_not_already_present_on_the_source_table_entry",
            ],
        },
        "invariants": {
            "table_count": len(projected_tables),
            "total_entries": total_entries,
            "total_identity_key_ungoverned": total_ungoverned_id,
            "total_claim_level_defaulted": total_default_claim,
            "total_source_ref_gaps": total_source_gap,
            "adapter_validation_passed": adapter_validation_passed,
            "lossless_projection": lossless,
        },
        "entries": entries,
    }


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=EXPORT_PATH,
        help="Where to write the export (default: exports/canonical_entry_index.yaml).",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    export = build_export()

    if not export["invariants"]["lossless_projection"]:
        print(
            "Refusing to write exports/canonical_entry_index.yaml: the live "
            "projection is not lossless. Fix the underlying table/adapter gap "
            "first (see python scripts/probe_canonical_entry_projection.py).",
            file=sys.stderr,
        )
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(export, sort_keys=False, allow_unicode=True, width=100)
    args.out.write_text(EXPORT_HEADER_COMMENT + body, encoding="utf-8")

    inv = export["invariants"]
    try:
        display_path = args.out.resolve().relative_to(REPO_ROOT)
    except ValueError:
        display_path = args.out
    print(
        f"Wrote {inv['total_entries']} entries across {inv['table_count']} tables "
        f"to {display_path} (lossless_projection=True)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
